language: go

git:
  depth: 100

# Build with the lastest versions of Go 1.5 and later
# See https://golang.org/dl/
go:
  - 1.5.4
  - 1.6.4
  - 1.7.6
  - 1.8.3
  - 1.9

install:
  - go get .

script:
  - openssl version
  - go build
  - ./build-without-openssl.bash
  - ./build.bash
  - ./gocryptfs -speed
  - ./test.bash
  - ./crossbuild.bash

# fuse on travis
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -qq fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
