[[constraint]]
  branch = "master"
  name = "github.com/hanwen/go-fuse"

[[constraint]]
  branch = "master"
  name = "github.com/jacobsa/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/rfjakob/eme"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"
